---
# tasks file for validations
- name: Check ansible version
  fail:
    msg: Use Ansible version 2.9 or greater to run this playbook
  when: ansible_version.full is version('2.9.9', '<')
  delegate_to: localhost

- name: Ensure Python libraries are installed
  python_requirements_info:
    dependencies:
    - python-hpilo
  register: _py_facts
  #when: "'HPE' in hostvars[item]['vendor']"
 # with_items:
 # - "{{ groups['masters'] }}"
 # - "{{ groups['workers'] | default([]) }}"

- name: Fail if Python modules are missing
  fail:
    msg: |
         Missing python module(s) {{ _py_facts.not_found }} on {{ groups['assisted_installer'][0] }}
  when:
  - _py_facts.not_found | length > 0
  - "'HPE' in hostvars[item]['vendor']"
  with_items:
  - "{{ groups['masters'] }}"
  - "{{ groups['workers'] | default([]) }}"

- name: Fail if remote_service_url is empty
  fail:
    msg: |
         The remote service URL is empty. Need a value similar to http://example.com:6000
  when: remote_service_url|length == 0

- name: Check for required VMware pre-reqs
  include_tasks: vmware.yml
  when: vcenter_datastore is defined

- name: Check for required oVirt pre-reqs
  include_tasks: ovirt.yml
  when: ovirt_storage_domain is defined
